pub mod accessors;
pub mod metadata;
pub mod routes;
pub mod services;
pub mod types;

pub const HEADER: &str = "// Generated by basecamp-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.\n\n";

/// An OpenAPI description as a rustdoc comment. Brackets and angle brackets are escaped so
/// prose never reads as an intra-doc link or an HTML tag, and a fenced block is marked
/// `text` so nothing in a description is compiled as a doctest.
pub fn doc_comment(description: Option<&str>, indent: &str) -> String {
    let Some(text) = description else {
        return String::new();
    };
    let mut out = String::new();
    let mut in_fence = false;
    for line in text.lines() {
        let line = line.trim_end();
        let trimmed = line.trim_start();
        if trimmed.starts_with("```") {
            in_fence = !in_fence;
            if in_fence && trimmed == "```" {
                out.push_str(&format!("{indent}/// ```text\n"));
            } else {
                out.push_str(&format!("{indent}/// {trimmed}\n"));
            }
        } else if in_fence {
            out.push_str(&format!("{indent}/// {line}\n"));
        } else if trimmed.is_empty() {
            out.push_str(&format!("{indent}///\n"));
        } else {
            let escaped = trimmed
                .replace('[', "\\[")
                .replace(']', "\\]")
                .replace('<', "\\<")
                .replace('>', "\\>");
            out.push_str(&format!("{indent}/// {escaped}\n"));
        }
    }
    out
}

pub fn string_literal(value: &str) -> String {
    format!("{value:?}")
}
