use std::fmt::Write;

pub(crate) mod accessors;
pub(crate) mod metadata;
pub(crate) mod routes;
pub(crate) mod services;
pub(crate) mod types;

pub(crate) const HEADER: &str = "// Generated by basecamp-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.\n\n";

/// An `OpenAPI` description as a rustdoc comment. Brackets and angle brackets are escaped so
/// prose never reads as an intra-doc link or an HTML tag, and a fenced block is marked
/// `text` so nothing in a description is compiled as a doctest.
pub(crate) fn doc_comment(description: Option<&str>, indent: &str) -> String {
    let Some(text) = description else {
        return String::new();
    };
    let mut out = String::new();
    let mut in_fence = false;
    for line in text.lines() {
        let line = line.trim_end();
        let trimmed = line.trim_start();
        if trimmed.starts_with("```") {
            in_fence = !in_fence;
            if in_fence && trimmed == "```" {
                writeln!(out, "{indent}/// ```text").unwrap();
            } else {
                writeln!(out, "{indent}/// {trimmed}").unwrap();
            }
        } else if in_fence {
            writeln!(out, "{indent}/// {line}").unwrap();
        } else if trimmed.is_empty() {
            writeln!(out, "{indent}///").unwrap();
        } else {
            let escaped = trimmed
                .replace('[', "\\[")
                .replace(']', "\\]")
                .replace('<', "\\<")
                .replace('>', "\\>");
            writeln!(out, "{indent}/// {escaped}").unwrap();
        }
    }
    out
}

pub(crate) fn string_literal(value: &str) -> String {
    format!("{value:?}")
}
