# Inherit from Rails/37signals omakase style
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "lib/basecamp/generated/**/*"

# Documentation not required for tests
Style/Documentation:
  Exclude:
    - "test/**/*"
