# 37signals house style
inherit_gem:
  rubocop-37signals: rubocop.yml

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - "vendor/**/*"
    - "lib/basecamp/generated/**/*"

# Documentation not required for tests
Style/Documentation:
  Exclude:
    - "test/**/*"
