go:
  - changed-files:
      - any-glob-to-any-file: "go/**"

typescript:
  - changed-files:
      - any-glob-to-any-file: "typescript/**"

ruby:
  - changed-files:
      - any-glob-to-any-file: "ruby/**"

kotlin:
  - changed-files:
      - any-glob-to-any-file: "kotlin/**"

swift:
  - changed-files:
      - any-glob-to-any-file: "swift/**"

spec:
  - changed-files:
      - any-glob-to-any-file:
          - "spec/**"
          - "openapi.json"
          - "behavior-model.json"

conformance:
  - changed-files:
      - any-glob-to-any-file: "conformance/**"

github-actions:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "*.md"
          - "docs/**"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "**/package.json"
          - "**/package-lock.json"
          - "**/go.mod"
          - "**/go.sum"
          - "**/Gemfile"
          - "**/Gemfile.lock"
          - "**/build.gradle.kts"
          - "**/gradle.lockfile"
          - "**/gradle/libs.versions.toml"
