// Generated by basecamp-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

//! The service accessors on [`AccountClient`], one per generated service.

use crate::client::AccountClient;
use crate::generated::services;

#[rustfmt::skip]
impl AccountClient {
    /// `Account` operations.
    pub fn account(&self) -> services::account::AccountService<'_> {
        services::account::AccountService::new(self)
    }

    /// `Widgets` operations.
    pub fn widgets(&self) -> services::widgets::WidgetsService<'_> {
        services::widgets::WidgetsService::new(self)
    }

}
