// Generated by basecamp-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

//! Per-operation behaviour from `behavior-model.json`: idempotency, read-onlyness and the
//! retry tuple SPEC §7's three gates consume.

use crate::route::{Backoff, OperationMetadata, RetryConfig};

/// `CreateWidget`.
#[rustfmt::skip]
pub static CREATE_WIDGET: OperationMetadata = OperationMetadata { operation: "CreateWidget", idempotent: false, readonly: false, retry: RetryConfig { max_attempts: 2, base_delay_ms: 1000, backoff: Backoff::Exponential, retry_on: &[429, 503] } };
/// `ListWidgets`.
#[rustfmt::skip]
pub static LIST_WIDGETS: OperationMetadata = OperationMetadata { operation: "ListWidgets", idempotent: false, readonly: true, retry: RetryConfig { max_attempts: 3, base_delay_ms: 1000, backoff: Backoff::Exponential, retry_on: &[429, 503] } };
/// `ReplaceWidget`.
#[rustfmt::skip]
pub static REPLACE_WIDGET: OperationMetadata = OperationMetadata { operation: "ReplaceWidget", idempotent: true, readonly: false, retry: RetryConfig { max_attempts: 3, base_delay_ms: 1000, backoff: Backoff::Exponential, retry_on: &[503] } };
/// `TrashWidget`.
#[rustfmt::skip]
pub static TRASH_WIDGET: OperationMetadata = OperationMetadata { operation: "TrashWidget", idempotent: true, readonly: false, retry: RetryConfig { max_attempts: 3, base_delay_ms: 1000, backoff: Backoff::Exponential, retry_on: &[429, 503] } };
/// `UpdateGadgetLogo`.
#[rustfmt::skip]
pub static UPDATE_GADGET_LOGO: OperationMetadata = OperationMetadata { operation: "UpdateGadgetLogo", idempotent: true, readonly: false, retry: RetryConfig { max_attempts: 2, base_delay_ms: 1000, backoff: Backoff::Exponential, retry_on: &[429, 503] } };

/// Every operation's metadata, in `operationId` order.
pub static OPERATIONS: &[&OperationMetadata] = &[
    &CREATE_WIDGET,
    &LIST_WIDGETS,
    &REPLACE_WIDGET,
    &TRASH_WIDGET,
    &UPDATE_GADGET_LOGO,
];
