// Generated by basecamp-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

//! Generated from `openapi.json` and `behavior-model.json`. Never edited by hand.

pub mod accessors;
pub mod metadata;
pub mod routes;
pub mod services;
pub mod types;

/// The Basecamp API version this SDK was generated against.
pub const API_VERSION: &str = "2026-01-02";

/// How many operations the model declares.
pub const OPERATION_COUNT: usize = 6;
