// Generated by basecamp-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

//! Every modelled route as public data: method, path, parameters and the behaviour the
//! model attaches to it.

use crate::generated::metadata;
use crate::http::Method;
use crate::route::{
    BodyKind, Pagination, ParamKind, Representation, Route, RouteParam, WriteSemantics,
};

/// `POST /widgets.json`.
pub static CREATE_WIDGET: Route = Route {
    id: "CreateWidget",
    service: "Widgets",
    method: Method::POST,
    path: "/widgets.json",
    pattern: "/widgets",
    resource_type: "widget",
    params: &[],
    body: BodyKind::Json,
    response: Representation::Json,
    pagination: Pagination::None,
    write: None,
    deprecated: false,
    metadata: &metadata::CREATE_WIDGET,
};

/// `GET /widgets/{widgetId}/progress.json`.
pub static GET_WIDGET_PROGRESS: Route = Route {
    id: "GetWidgetProgress",
    service: "Widgets",
    method: Method::GET,
    path: "/widgets/{widgetId}/progress.json",
    pattern: "/widgets/{widgetId}/progress",
    resource_type: "widget_progress",
    params: &[RouteParam {
        name: "widgetId",
        kind: ParamKind::Int64,
    }],
    body: BodyKind::None,
    response: Representation::Json,
    pagination: Pagination::Link {
        key: Some("events"),
        total_count_header: Some("X-Total-Count"),
    },
    write: None,
    deprecated: false,
    metadata: &metadata::GET_WIDGET_PROGRESS,
};

/// `GET /widgets.json`.
pub static LIST_WIDGETS: Route = Route {
    id: "ListWidgets",
    service: "Widgets",
    method: Method::GET,
    path: "/widgets.json",
    pattern: "/widgets",
    resource_type: "widget",
    params: &[],
    body: BodyKind::None,
    response: Representation::Json,
    pagination: Pagination::Link {
        key: None,
        total_count_header: Some("X-Total-Count"),
    },
    write: None,
    deprecated: false,
    metadata: &metadata::LIST_WIDGETS,
};

/// `PUT /buckets/{bucketId}/widgets/{widgetId}`.
pub static REPLACE_WIDGET: Route = Route {
    id: "ReplaceWidget",
    service: "Widgets",
    method: Method::PUT,
    path: "/buckets/{bucketId}/widgets/{widgetId}",
    pattern: "/buckets/{bucketId}/widgets/{widgetId}",
    resource_type: "widget",
    params: &[
        RouteParam {
            name: "bucketId",
            kind: ParamKind::Int64,
        },
        RouteParam {
            name: "widgetId",
            kind: ParamKind::Int64,
        },
    ],
    body: BodyKind::Json,
    response: Representation::Json,
    pagination: Pagination::None,
    write: Some(&WriteSemantics {
        clears_omitted: true,
        preserved_on_omission: &["color"],
    }),
    deprecated: false,
    metadata: &metadata::REPLACE_WIDGET,
};

/// `DELETE /buckets/{bucketId}/widgets/{widgetId}`.
pub static TRASH_WIDGET: Route = Route {
    id: "TrashWidget",
    service: "Widgets",
    method: Method::DELETE,
    path: "/buckets/{bucketId}/widgets/{widgetId}",
    pattern: "/buckets/{bucketId}/widgets/{widgetId}",
    resource_type: "widget",
    params: &[
        RouteParam {
            name: "bucketId",
            kind: ParamKind::Int64,
        },
        RouteParam {
            name: "widgetId",
            kind: ParamKind::Int64,
        },
    ],
    body: BodyKind::None,
    response: Representation::Empty,
    pagination: Pagination::None,
    write: None,
    deprecated: false,
    metadata: &metadata::TRASH_WIDGET,
};

/// `PUT /account/logo.json`.
pub static UPDATE_GADGET_LOGO: Route = Route {
    id: "UpdateGadgetLogo",
    service: "Account",
    method: Method::PUT,
    path: "/account/logo.json",
    pattern: "/account/logo",
    resource_type: "gadget_logo",
    params: &[],
    body: BodyKind::Multipart { field: "logo" },
    response: Representation::Empty,
    pagination: Pagination::None,
    write: None,
    deprecated: false,
    metadata: &metadata::UPDATE_GADGET_LOGO,
};

/// Every route the SDK knows, one per operation, in `operationId` order.
pub static ROUTES: &[&Route] = &[
    &CREATE_WIDGET,
    &GET_WIDGET_PROGRESS,
    &LIST_WIDGETS,
    &REPLACE_WIDGET,
    &TRASH_WIDGET,
    &UPDATE_GADGET_LOGO,
];
