// Generated by basecamp-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

//! The request and response shapes the Basecamp API speaks.

#![allow(deprecated, clippy::doc_markdown)]

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

use crate::types::{AuthRoutableUrl, Date, DateTime, FlexibleTime, SensitiveString};

/// The `CreateWidgetRequestContent` shape of the Basecamp API.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CreateWidgetRequestContent {
    /// `name`.
    #[serde(default)]
    pub name: String,
    /// `color`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    /// `due_on`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub due_on: Option<Date>,
    /// `owner`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub owner: Option<Owner>,
}

/// `CreateWidgetResponseContent`.
pub type CreateWidgetResponseContent = Widget;

/// `ListWidgetsResponseContent`.
pub type ListWidgetsResponseContent = Vec<Widget>;

/// A widget.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct Widget {
    /// `id`.
    #[serde(default, deserialize_with = "crate::types::flexible_i64::deserialize")]
    pub id: i64,
    /// `name`.
    #[serde(default)]
    pub name: String,
    /// Always present; `null` when unset.
    #[serde(deserialize_with = "serde::Deserialize::deserialize")]
    pub color: Option<String>,
    /// `created_at`.
    pub created_at: DateTime,
    /// `starts_at`.
    #[serde(deserialize_with = "serde::Deserialize::deserialize")]
    pub starts_at: Option<FlexibleTime>,
    /// `width`.
    #[serde(
        default,
        deserialize_with = "crate::types::flex_int::deserialize",
        skip_serializing_if = "Option::is_none"
    )]
    pub width: Option<i32>,
    /// `email`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<SensitiveString>,
    /// `download_url`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub download_url: Option<AuthRoutableUrl>,
    /// `parent`.
    #[serde(deserialize_with = "serde::Deserialize::deserialize")]
    pub parent: Option<Owner>,
    /// `children`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub children: Option<Vec<Widget>>,
    /// `labels`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<BTreeMap<String, String>>,
    /// `kind`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<Kind>,
    /// `extra`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extra: Option<serde_json::Value>,
    /// `legacy`.
    #[deprecated(note = "gone")]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub legacy: Option<Legacy>,
}

/// The `Owner` shape of the Basecamp API.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Owner {
    /// `id`.
    #[serde(default)]
    pub id: i64,
}

/// The `Kind` values the Basecamp API declares.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default)]
#[non_exhaustive]
pub enum Kind {
    #[default]
    /// `basic`.
    Basic,
    /// `fancy`.
    Fancy,
    /// A value this SDK does not know, kept as the API sent it so a read-modify-write
    /// round-trips it.
    Unknown(String),
}

impl Kind {
    /// The value as the API spells it.
    pub fn as_str(&self) -> &str {
        match self {
            Kind::Basic => "basic",
            Kind::Fancy => "fancy",
            Kind::Unknown(value) => value,
        }
    }
}

impl From<&str> for Kind {
    fn from(value: &str) -> Self {
        match value {
            "basic" => Kind::Basic,
            "fancy" => Kind::Fancy,
            other => Kind::Unknown(other.to_string()),
        }
    }
}

impl std::fmt::Display for Kind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Serialize for Kind {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for Kind {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = String::deserialize(deserializer)?;
        Ok(Self::from(value.as_str()))
    }
}

/// The `Legacy` shape of the Basecamp API.
#[deprecated(note = "gone")]
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct Legacy {
    /// `url`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

/// `LabelMap`.
pub type LabelMap = BTreeMap<String, Vec<String>>;

/// A raw byte payload, sent as the request body.
pub type UpdateGadgetLogoInputPayload = Vec<u8>;
