// Generated by basecamp-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

//! Account operations.

#![allow(
    clippy::too_many_arguments,
    clippy::wildcard_imports,
    clippy::doc_markdown
)]

use bytes::Bytes;

use crate::client::AccountClient;
use crate::error::Error;
use crate::generated::routes;

/// `Account` operations, sent through one [`AccountClient`].
#[derive(Debug, Clone, Copy)]
pub struct AccountService<'a> {
    client: &'a AccountClient,
}

impl<'a> AccountService<'a> {
    pub(crate) fn new(client: &'a AccountClient) -> Self {
        Self { client }
    }

    /// The client this service sends through.
    pub fn client(&self) -> &'a AccountClient {
        self.client
    }

    /// `PUT /account/logo.json` — idempotent; retries up to 2 attempt(s) on 429, 503.
    pub async fn update_logo(
        &self,
        filename: &str,
        content_type: &str,
        body: Bytes,
    ) -> Result<(), Error> {
        let mut operation = self.client.operation(&routes::UPDATE_GADGET_LOGO, &[]);
        operation.multipart("logo", filename, content_type, &body);
        self.client.send_unit(operation).await
    }
}
