// Generated by basecamp-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

//! One module per service, each a handle on an [`AccountClient`](crate::client::AccountClient).

pub mod account;
pub mod widgets;
