// Generated by basecamp-sdk-generator from openapi.json and behavior-model.json. DO NOT EDIT.

//! Widgets operations.

#![allow(
    clippy::too_many_arguments,
    clippy::wildcard_imports,
    clippy::doc_markdown
)]

use crate::client::AccountClient;
use crate::error::Error;
use crate::generated::routes;
#[allow(unused_imports)]
use crate::generated::types::*;
use crate::pagination::Page;

/// Optional query parameters for `ListWidgets`.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct ListWidgetsParams {
    /// Filter by status.
    pub status: Option<String>,
    /// `page`.
    pub page: Option<i32>,
    /// `tag_ids[]`.
    pub tag_ids: Option<Vec<i64>>,
    /// `type`.
    #[deprecated(note = "prefer kinds[].")]
    pub r#type: Option<String>,
}

/// Optional query parameters for `GetWidgetProgress`.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct GetWidgetProgressParams {
    /// `page`.
    pub page: Option<i32>,
}

impl crate::pagination::PageItems for GetWidgetProgressResponseContent {
    type Item = Widget;

    fn into_items(self) -> Vec<Widget> {
        self.events
    }
}

/// `Widgets` operations, sent through one [`AccountClient`].
#[derive(Debug, Clone, Copy)]
pub struct WidgetsService<'a> {
    client: &'a AccountClient,
}

impl<'a> WidgetsService<'a> {
    pub(crate) fn new(client: &'a AccountClient) -> Self {
        Self { client }
    }

    /// The client this service sends through.
    pub fn client(&self) -> &'a AccountClient {
        self.client
    }

    /// `POST /widgets.json` — not idempotent, sent exactly once.
    pub async fn create_widget(
        &self,
        body: &CreateWidgetRequestContent,
    ) -> Result<CreateWidgetResponseContent, Error> {
        let mut operation = self.client.operation(&routes::CREATE_WIDGET, &[]);
        operation.json(body)?;
        self.client.send(operation).await
    }

    /// Lists widgets.
    ///
    /// See \[the docs\](https://example.com) and \<b\>bold\</b\>.
    ///
    /// `GET /widgets.json` — idempotent; retries up to 3 attempt(s) on 429, 503.
    #[allow(deprecated)]
    pub async fn list_widgets(
        &self,
        params: &ListWidgetsParams,
    ) -> Result<Page<ListWidgetsResponseContent>, Error> {
        let mut operation = self.client.operation(&routes::LIST_WIDGETS, &[]);
        operation.query_optional("status", params.status.as_ref());
        operation.query_optional("page", params.page.as_ref());
        operation.query_list_optional("tag_ids[]", params.tag_ids.as_deref());
        operation.query_optional("type", params.r#type.as_ref());
        self.client.send_page(operation).await
    }

    /// `PUT /buckets/{bucketId}/widgets/{widgetId}` — idempotent; retries up to 3 attempt(s) on 503.
    pub async fn replace_widget(
        &self,
        bucket_id: i64,
        widget_id: i64,
        body: &CreateWidgetRequestContent,
    ) -> Result<CreateWidgetResponseContent, Error> {
        let mut operation = self
            .client
            .operation(&routes::REPLACE_WIDGET, &[&bucket_id, &widget_id]);
        operation.json(body)?;
        self.client.send(operation).await
    }

    /// `DELETE /buckets/{bucketId}/widgets/{widgetId}` — idempotent; retries up to 3 attempt(s) on 429, 503.
    pub async fn trash_widget(&self, bucket_id: i64, widget_id: i64) -> Result<(), Error> {
        let operation = self
            .client
            .operation(&routes::TRASH_WIDGET, &[&bucket_id, &widget_id]);
        self.client.send_unit(operation).await
    }

    /// A widget's activity, page by page.
    ///
    /// Each page is the envelope; its `events` member is the collection, which [`AccountClient::collect_all`] and [`AccountClient::items`] gather across pages. The other members are on every page: read them off the first.
    ///
    /// `GET /widgets/{widgetId}/progress.json` — idempotent; retries up to 3 attempt(s) on 429, 503.
    pub async fn widget_progress(
        &self,
        widget_id: i64,
        params: &GetWidgetProgressParams,
    ) -> Result<Page<GetWidgetProgressResponseContent>, Error> {
        let mut operation = self
            .client
            .operation(&routes::GET_WIDGET_PROGRESS, &[&widget_id]);
        operation.query_optional("page", params.page.as_ref());
        self.client.send_page(operation).await
    }
}
