"""Fixture for the stale-module sweep in the Python service generator (#757).

Nothing else executes the deletion branch. `check-python-service-drift.sh`
regenerates into a fresh temp directory, so the sweep never has a corpse to
find there, and a live `make generate` only ever confirms the current roster —
the branch that unlinks a file has, until now, run in no test at all. These
cases build a directory holding every kind of file the sweep must tell apart,
run the real thing over it, and assert on what is left on disk.

The `types.py` case is the one worth stating outright: the types generator emits
it one directory up carrying the *identical* `@generated` marker line, so a
predicate matching the marker alone deletes it the first time someone points
`--output` at `generated/` instead of `generated/services/`. Requiring the
service base import as well is what keeps it, and this is where that stays true.

`main` gets its own two cases, because the predicate can be right while the
wiring is wrong: one proves the sweep is actually called after the emit loop,
the other that the self-check refuses to run at all once the emitted preamble
and the constants the sweep looks for disagree.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent / "scripts"))
import generate_services  # noqa: E402
from generate_services import (  # noqa: E402
    SERVICE_MODULE_BASE_IMPORT,
    SERVICE_MODULE_MARKER,
    remove_stale_files,
)

OPENAPI = Path(__file__).parent.parent.parent / "openapi.json"

# A module named by no mapping, so `main` cannot emit it: the corpse a renamed
# or dropped service leaves behind.
STALE_MODULE = "fanfares.py"

# A module `main` does emit, so the "written by this run" guard has something to
# protect.
EMITTED_MODULE = "projects.py"


def service_module(class_name: str) -> str:
    """A head shaped like one this generator emits: marker *and* base import."""
    return "\n".join(
        [
            SERVICE_MODULE_MARKER,
            "",
            "from __future__ import annotations",
            "",
            SERVICE_MODULE_BASE_IMPORT,
            "",
            "",
            f"class {class_name}Service(BaseService):",
            "    pass",
            "",
        ]
    )


def populate(output_dir: Path) -> None:
    """Write one file of every kind the sweep has to distinguish."""
    # 1. A generated service module nothing emits any more.
    (output_dir / STALE_MODULE).write_text(service_module("Fanfares"), encoding="utf-8")

    # 2. A generated service module that is still emitted.
    (output_dir / EMITTED_MODULE).write_text(service_module("Projects"), encoding="utf-8")

    # 3. The hand-written base modules, which live under `generated/` by
    #    exception (AGENTS.md Hard Rule 1). Their real heads carry no marker.
    for base in ("_base.py", "_async_base.py"):
        (output_dir / base).write_text(
            "from __future__ import annotations\n\n\nclass BaseService:\n    pass\n",
            encoding="utf-8",
        )

    # 4. A hand-written module with no marker at all.
    (output_dir / "hand_written.py").write_text(
        '"""Not generated by anything."""\n\nVALUE = 1\n',
        encoding="utf-8",
    )

    # 5. The barrel, marker-carrying but importing no base — the shape
    #    `generate_init_file` emits.
    (output_dir / "__init__.py").write_text(
        f"{SERVICE_MODULE_MARKER}\n\nfrom basecamp.generated.services.projects import ProjectsService\n",
        encoding="utf-8",
    )

    # 6. The types module, one directory up in the tracked tree but right here
    #    if `--output` names the parent: the identical marker, no base import.
    (output_dir / "types.py").write_text(
        f"{SERVICE_MODULE_MARKER}\n\nfrom __future__ import annotations\n\nfrom typing import TypedDict\n",
        encoding="utf-8",
    )


def names_on_disk(output_dir: Path) -> set[str]:
    return {p.name for p in output_dir.glob("*.py")}


@pytest.fixture()
def swept(tmp_path: Path) -> Path:
    """A populated directory, after a real sweep that emitted two of its files."""
    populate(tmp_path)
    remove_stale_files(tmp_path, [EMITTED_MODULE, "__init__.py"])
    return tmp_path


def test_removes_a_generated_module_no_longer_emitted(swept: Path):
    assert STALE_MODULE not in names_on_disk(swept)


def test_keeps_a_module_this_run_emitted(swept: Path):
    # Same content as the stale one, so only membership in the emitted set can
    # be what saves it.
    assert EMITTED_MODULE in names_on_disk(swept)


def test_keeps_the_hand_written_base_modules(swept: Path):
    # Excluded twice over — by the `_` prefix and by carrying no marker — and
    # either exclusion suffices, so this holds the property rather than one of
    # the two clauses that delivers it.
    assert {"_base.py", "_async_base.py"} <= names_on_disk(swept)


def test_keeps_an_unmarked_hand_written_module(swept: Path):
    assert "hand_written.py" in names_on_disk(swept)


def test_keeps_the_marker_carrying_barrel(swept: Path):
    assert "__init__.py" in names_on_disk(swept)


def test_keeps_a_types_module_carrying_only_the_marker(swept: Path):
    # The marker is byte-identical to a service module's. Only the missing base
    # import distinguishes it, so a marker-only predicate deletes the generated
    # TypedDicts of the whole SDK here.
    assert "types.py" in names_on_disk(swept)


def run_main(monkeypatch: pytest.MonkeyPatch, output_dir: Path) -> None:
    monkeypatch.setattr(
        sys,
        "argv",
        ["generate_services.py", "--openapi", str(OPENAPI), "--output", str(output_dir)],
    )
    generate_services.main()


def test_main_sweeps_stale_modules_after_emitting(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    populate(tmp_path)

    run_main(monkeypatch, tmp_path)

    remaining = names_on_disk(tmp_path)
    assert STALE_MODULE not in remaining
    # The emit loop's own output is intact, and so is everything the sweep is
    # not entitled to touch.
    assert EMITTED_MODULE in remaining
    assert {"_base.py", "_async_base.py", "hand_written.py", "types.py", "__init__.py"} <= remaining
    # Non-vacuity floor. Every name above was already on disk before `main` ran,
    # so a `main` that emitted nothing would satisfy them all: this run must have
    # produced the real roster, and rewritten the placeholder standing in for one
    # of its modules, for "emitted this run" to mean anything here. The floor sits
    # well under the real count so it is not a second constant to maintain.
    assert len(remaining) > 40
    assert (tmp_path / EMITTED_MODULE).read_text(encoding="utf-8") != service_module("Projects")


def test_main_refuses_when_its_preamble_stops_matching_the_sweep(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
):
    """A preamble change that stops matching must fail, not sweep nothing.

    The sweep recognizes its own past output by content. Rename the base import
    in the emitted preamble and leave the constants alone and every future file
    stops being recognizable — silently, since a no-op sweep deletes nothing and
    reports nothing.
    """
    populate(tmp_path)

    def renamed_base_import(service: dict) -> str:
        return "\n".join(
            [
                SERVICE_MODULE_MARKER,
                "",
                SERVICE_MODULE_BASE_IMPORT.replace("_base", "_base_service"),
                "",
                "",
                f"class {service['name']}Service(BaseService):",
                "    pass",
                "",
            ]
        )

    monkeypatch.setattr(generate_services, "generate_service_file", renamed_base_import)

    with pytest.raises(SystemExit) as exit_info:
        run_main(monkeypatch, tmp_path)

    assert exit_info.value.code == 1
    stderr = capsys.readouterr().err
    assert "SERVICE_MODULE_MARKER" in stderr
    assert "SERVICE_MODULE_BASE_IMPORT" in stderr
    # Fails closed: it exits before the sweep, so nothing is unlinked on the
    # strength of a predicate the generator has just shown it cannot trust.
    assert STALE_MODULE in names_on_disk(tmp_path)
